### ISSUE TITLE
Configuration option to open log may open Explorer in the background and has latency

### ISSUE THREAD

**Issue by itagagaki** [1Remote/1Remote#777] opened 2024-11-19 09:06 UTC
Options > General > [Log file] is not editable.
And the loupe button to the right of it doesn't seem to work.

**Comment by VShawn** [comment] 2024-11-19 10:53
Yes log input box was designed to be non-editable. 

The button on the right is to open the directory where the log files are located.

**Comment by itagagaki** [comment] 2024-11-19 11:11
Okay, but if the path is long, I can only see from the beginning to the middle. So I don't know the location or the filename.

And no window opens when I click the button.

**Comment by VShawn** [comment] 2024-11-20 01:02
https://github.com/user-attachments/assets/a41a308e-5035-40fc-ae14-32915b1b2c6f

though the path is long, you can drag text to see all characters. 

the button works fine on my end, so I have no clue what's going on.

**Comment by itagagaki** [comment] 2024-11-20 03:26
I just tried the same thing and was able to do it. This is strange because I couldn't do either yesterday. I'll close it for now and report back if I find anything new.

**Comment by itagagaki** [comment] 2024-12-01 09:09
Reproduced, so I reopen this.
Just now, the file selection dialog did not appear.
Sometimes it appears after restarting the application, and sometimes it still does not appear.

I don't know what the cause is, but is it possible that it is displayed at coordinates outside the desktop? I use multiple monitors, could that have something to do with this?

**Comment by VShawn** [comment] 2024-12-04 01:04
I don't know the cause either.

But the code to launch explorer.exe to open the log file is as follows. I think such simple code shouldn't have any issues.

[[Link]](https://github.com/VShawn/Shawn.Utils/blob/de85b238a86a6161d878b185ad47c624ad0d17ea/Shawn.Utils.Wpf/FileSystem/SelectFileHelper.cs#L154-L162)

I initially suspected it was a bug with Windows 11, as I've encountered bugs since Win11 refacted  their explorer. However, I tested it on version 23H2 22631.4317, and open the log works fine.

**Comment by itagagaki** [comment] 2024-12-04 05:11
Hmmm... OK, I'll try to find a way to investigate.

**Comment by itagagaki** [comment] 2024-12-05 10:46
I have not reproduced this since, but we have noticed that when Explorer is launched, it is often completely hidden behind other windows. I would like it to appear in front of every window, but this may be unavoidable due to Windows specifications.
I have done some research and found that this might also be related to the `ForegroundLockTimeout` value in the registry.

If I come across a phenomenon other than hiding behind other windows, I will use this tool to investigate.
[GUIPropView - View and set Windows properties from command line or GUI](https://www.nirsoft.net/utils/gui_prop_view.html)

**Comment by majkinetor** [comment] 2024-12-05 10:55
Such a trivial thing as starting explorer in given path should not cause concern. I can't reproduce the problem.

This can be brute forced pretty easily (start explorer, get its hwnd, activate it). It seems something is stealing focus on your OS.

**Comment by VShawn** [comment] 2024-12-05 11:48
`file selection dialogs` and `open the log file location` are two different things. while the `file selection dialogs` calls system APIs, and `open the log file location` by launches a process. It seems that there was an issue with the process launch on your end.

**Comment by itagagaki** [comment] 2024-12-05 12:03
In my environment (Windows 10 Pro 22H2 64bit), explorer.exe did not appear at the top when launched with the /select option.

How does it work on yours?

https://github.com/user-attachments/assets/f99a92b6-cbe4-4124-9926-8c5d4b9b76ad

**Comment by majkinetor** [comment] 2024-12-05 12:59
`select` or not, its the same here. Windows 11 and 10 here. 

Like I said, this is a local problem, this situation of yours is atypical. 

Besides, even if you can't fix it, is it really that important? In any case, if its about select, lets just remove it.

**Comment by itagagaki** [comment] 2024-12-05 13:10
Is it important or not?
Reported and continue to investigate because I saw a problem on my end, because I have no evidence yet that this is a local problem.
That's all I do.

**Comment by VShawn** [comment] 2024-12-05 13:12
https://github.com/user-attachments/assets/371aae41-789e-4275-a0d3-11efac4d0594

just sharing how it works on my end

**Comment by VShawn** [comment] 2024-12-05 13:19
Any error feedback is encouraged, regardless of whether the bug is important or not. we investigate - if we can fix it, we'll repair it; if we can't find the cause, we suspend and work around it.

**Comment by itagagaki** [comment] 2024-12-05 14:28
One thing I noticed as a result of my investigation.

The problem only occurs when the Explorer ribbon is expanded. This is exactly the same on my other PC (which has the same version of Windows).

However, VShawn does not have the problem with the expanded ribbon, so I still don't know what the root cause is.

https://github.com/user-attachments/assets/ba881c99-a198-4399-9390-62b65727409c

**Comment by majkinetor** [comment] 2024-12-05 16:25
You should manage time my friend :) This doesnt deserve it

**Comment by itagagaki** [comment] 2024-12-05 16:45
Why should you complain to me?
If you don't want to do anything about it, well, you don't have to. And stay out of it.
Don't tell me what to do.

**Comment by majkinetor** [comment] 2024-12-05 17:11
UUuu, we are a bit touchy...

**Comment by majkinetor** [comment] 2024-12-05 17:12
Closing this as local problem.

**Closed by majkinetor** 2024-12-05 17:12 UTC
Labels: bug, area-configuration

**Comment by itagagaki** [comment] 2024-12-05 17:14
Hey, which is rude?

**Comment by itagagaki** [comment] 2024-12-05 17:18
No, it is not. I asked who is rude, me or you?

**Comment by itagagaki** [comment] 2024-12-05 17:18
> Closing this as local problem.

No evidence

**Comment by majkinetor** [comment] 2024-12-05 17:21
> No, it is not. I asked who is rude, me or you?

I don't want irrelevant spam here, dominating discussions (few are OK). If there is anything more you want to know, contact me via email.

> No evidence

Your N=1 evidence is lower then our N>1 evidence.

**Comment by itagagaki** [comment] 2024-12-05 17:25
> Your N=1 evidence is lower then our N>1 evidence.

Incorrect. N=2 on my end now.

**Comment by itagagaki** [comment] 2024-12-05 17:29
It is premature to assume without evidence that unexplained events are due to very limited and special circumstances.

**Comment by VShawn** [comment] 2024-12-06 02:54
I stand by @itagagaki on this one. Although I believe this bug is indeed not critical, the contributors who spent time helping investigate and test should be couraged not be discouraged.

----

BTW teting on my another win11

https://github.com/user-attachments/assets/759c05fd-a05c-499b-b0c3-2326ba52e9b6

**Comment by itagagaki** [comment] 2024-12-11 06:49
This is not a local issue.

For some time now (a few years?), Windows 10 has been experiencing a phenomenon where new windows are hidden behind other windows. The conditions under which this happens are unclear, ranging from noticeable to not so noticeable, etc. Often, even important UAC dialogs are hidden behind them and the user is unaware of it. I suspect that there is a bug in Windows that is not easy to fix because of its inconvenient specifications; as for Windows 11, I don't know because I haven't used it yet.

This issue is probably also due to this Windows bug. It's probably impossible to work around on the application side, and I don't think there should be any funny little tricks, so this issue should be closed as is.

**Comment by majkinetor** [comment] 2024-12-11 13:03
Never personally experienced this, with massive WIndows exposure.

Here are few references I found
- https://answers.microsoft.com/en-us/windows/forum/all/application-windows-opening-in-the-background/087e0680-918c-4136-8e07-e7684f0a7f2a
- https://answers.microsoft.com/en-us/windows/forum/all/win10-1809-pop-up-window-behind-main-window-same/993b0275-0bae-46a5-8acc-7bf363f153bb

Answer suggests its a local issue.

**Comment by itagagaki** [comment] 2024-12-11 13:46
> Answer suggests its a local issue.

You haven't experienced it, you haven't even found a case of it, but that's no reason to dismiss it as a local issue. Why should you insist? What would be the downside for you if you did not?

If it's not limited to 1Remote, it's not just me. I have heard unspecified reports in Japan. I also have a lot of experience and I have the same reports within the Japanese tech community. One possibility I can think of is that it is only happening in Japan, but that is not well proven either. I even tried changing my Windows language setting to English for a change, but the situation was the same.

Again, why insist?

You might say that it is you who is insisting on this, but I am just writing about what is actually happening. Including community canvassing. I don't know what your point is in denying it.

**Comment by majkinetor** [comment] 2024-12-11 13:56
> Again, why insist?

I do not insist. Its hypothesis based on the facts shown so far. 

As of why, its because of time management, like I noted. I will not go further into this for sure nor I have any problem with anybody fixing this. We are better to look into real issues, of which there are many.

**Comment by itagagaki** [comment] 2024-12-11 14:07
Your time is yours to manage. I will manage my time. There has been no need for you to make unfounded hypotheses about this matter, and there never will be.

**Comment by itagagaki** [comment] 2024-12-11 14:14
> You seem to approach this very emotionally for some reason and act like you are attacked.

I just take an interest in the issue, do the research and investigation, and share the results. If you say that interrupting that is an attack, then I suppose it is.

**Comment by majkinetor** [comment] 2024-12-11 14:16
I am not talking about your time. 

You seem to have problem understanding English well too, so I will move on.

**Comment by itagagaki** [comment] 2024-12-11 14:18
> You seem to have problem understanding English well too

rude

**Comment by itagagaki** [comment] 2024-12-11 14:23
There is one more thing I do not understand. Why @majkinetor has the discretion to manage this product.

**Comment by VShawn** [comment] 2024-12-12 01:08
Uh-huh?
